apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: multicluster-global-hub-grafana
  name: multicluster-global-hub:multicluster-global-hub-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-global-hub:multicluster-global-hub-grafana
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-grafana
  namespace: {{.Namespace}}
