{{- if .EnableMetrics }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-global-hub:grafana-cluster-monitoring-binding
  labels:
    app: multicluster-global-hub-grafana
subjects:
  - kind: ServiceAccount
    name: multicluster-global-hub-grafana
    namespace: {{.Namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
{{- end }}
