apiVersion: v1
kind: ConfigMap
metadata:
  name: multicluster-global-hub-agent-config
  namespace: {{.Namespace}}
data:
  managedClusters: "5s"
  policies: "5s"
  hubClusterInfo: "60s"
  hubClusterHeartbeat: "60s"
  aggregationLevel: full
  enableLocalPolicies: "true"
  logLevel: "info"
