{{- if .InstallHostedMode -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.TransportConfigSecret}}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
type: Opaque
data:
  "kafka.yaml": {{.KafkaConfigYaml}}
{{- end -}}
