apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: {{.Namespace}}
  labels:
    global-hub.open-cluster-management.io/local-resource: ""
spec:
  clusterSet: default