apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default
  namespace: open-cluster-management
  labels:
    global-hub.open-cluster-management.io/managed-by: multicluster-global-hub-operator
spec:
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
    - scoreCoordinate:
        builtIn: ResourceAllocatableMemory
        type: BuiltIn
      weight: 1
    - scoreCoordinate:
        builtIn: Steady
        type: BuiltIn
      weight: 3
    mode: Exact