---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-rbac
  namespace: open-cluster-management
  labels:
    name: multicluster-global-hub-rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-global-hub-rbac
  template:
    metadata:
      labels:
        name: multicluster-global-hub-rbac
    spec:
      serviceAccountName: multicluster-global-hub-rbac
      containers:
        - name: multicluster-global-hub-rbac
          image: {{.Image}}
          imagePullPolicy: Always
          args:
          - "/data/opa_authorization.rego"
          - "/data/data.json"
          - "/data/role_bindings.yaml"
          - "--tls-cert-file=/certs/tls.crt"
          - "--tls-private-key-file=/certs/tls.key"
          - "--authorization=basic"
          volumeMounts:
           - readOnly: true
             mountPath: /data
             name: opa-data
           - readOnly: true
             mountPath: /certs
             name: certs
      volumes:
       - name: opa-data
         secret:
           secretName: opa-data
       - name: certs
         secret:
           secretName: multicluster-global-hub-rbac-certs
