---
apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-rbac
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-rbac
    service: multicluster-global-hub-rbac
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-rbac-certs
spec:
  ports:
  - port: 8181
    name: http
  selector:
    name: multicluster-global-hub-rbac
