---
apiVersion: v1
kind: Service
metadata:
  name: hub-of-hubs-rbac
  namespace: open-cluster-management
  labels:
    name: hub-of-hubs-rbac
    service: hub-of-hubs-rbac
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hub-of-hubs-rbac-certs
spec:
  ports:
  - port: 8181
    name: http
  selector:
    name: hub-of-hubs-rbac
