---
apiVersion: v1
kind: Service
metadata:
  name: multicluster-globalhub-rbac
  namespace: open-cluster-management
  labels:
    name: multicluster-globalhub-rbac
    service: multicluster-globalhub-rbac
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-globalhub-rbac-certs
spec:
  ports:
  - port: 8181
    name: http
  selector:
    name: multicluster-globalhub-rbac
