kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-globalhub-agent
  namespace: {{.HostedClusterNamespace}}
subjects:
- kind: ServiceAccount
  name: multicluster-globalhub-agent
  namespace: {{.HostedClusterNamespace}}
roleRef:
  kind: Role
  name: multicluster-globalhub-agent
  apiGroup: rbac.authorization.k8s.io
