apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  labels:
    open-cluster-management.io/addon-name: config-policy-controller
  name: addon-config-policy-controller-${HYPERSHIFT_MANAGED_CLUSTER_NAME}-hosted
  namespace: ${HYPERSHIFT_MGMT_CLUSTER}
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: config-policy-controller
          chart: config-policy-controller-2.2.0
          heritage: Helm
          release: config-policy-controller
        name: config-policy-controller-hosted
        namespace: klusterlet-${HYPERSHIFT_MANAGED_CLUSTER_NAME}
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: config-policy-controller
            release: config-policy-controller
        strategy: {}
        template:
          metadata:
            annotations:
              target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
            creationTimestamp: null
            labels:
              app: config-policy-controller
              chart: config-policy-controller-2.2.0
              heritage: Helm
              release: config-policy-controller
          spec:
            affinity: {}
            containers:
            - args:
              - --kubeconfig=/spoke/config/kubeconfig
              - --hubconfig-secret-ns=klusterlet-${HYPERSHIFT_MANAGED_CLUSTER_NAME}
              - --enable-lease=true
              - --cluster-name=${HYPERSHIFT_MANAGED_CLUSTER_NAME}
              - --log-encoder=console
              - --log-level=0
              - --v=-1
              command:
              - config-policy-controller
              env:
              - name: WATCH_NAMESPACE
                value: ${HYPERSHIFT_MANAGED_CLUSTER_NAME}
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: config-policy-controller
              - name: HTTP_PROXY
              - name: HTTPS_PROXY
              - name: NO_PROXY
              image: quay.io/morvencao/config-policy-controller:latest
              imagePullPolicy: IfNotPresent
              name: config-policy-controller
              resources:
                limits:
                  memory: 512Mi
                requests:
                  memory: 128Mi
              volumeMounts:
              - mountPath: /spoke/config
                name: spoke-kubeconfig-secret
                readOnly: true
            imagePullSecrets:
            - name: open-cluster-management-image-pull-credentials
            securityContext:
              runAsNonRoot: true
            serviceAccount: config-policy-controller-sa
            tolerations:
            - effect: NoSchedule
              key: dedicated
              operator: Equal
              value: infra
            - effect: NoSchedule
              key: node-role.kubernetes.io/infra
              operator: Exists
            volumes:
            - name: klusterlet-config
              secret:
                secretName: config-policy-controller-hub-kubeconfig
            - name: spoke-kubeconfig-secret
              secret:
                defaultMode: 420
                secretName: external-managed-kubeconfig
      status: {}
    - apiVersion: v1
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
      kind: ServiceAccount
      metadata:
        labels:
          app: config-policy-controller
          chart: config-policy-controller-2.2.0
          heritage: Helm
          release: config-policy-controller
        name: config-policy-controller-sa
        namespace: klusterlet-${HYPERSHIFT_MANAGED_CLUSTER_NAME}
