apiVersion: v1
kind: Secret
metadata:
  name: inventory-api-config
  namespace: {{.Namespace}}
type: Opaque
stringData:
  inventory-api-config.yaml: |
    server:
      http:
        address: 0.0.0.0:8081
        keyfile: /inventory/certs/tls.key
        certfile: /inventory/certs/tls.crt
        client-ca-file: /inventory/client-certs/ca.crt
      grpc:
        address: 0.0.0.0:9081
    authn:
      allow-unauthenticated: false
    authz:
      impl: allow-all
    eventing:
      eventer: stdout
      kafka:
    storage:
      database: postgres
      postgres:
        host: {{.PostgresHost}}
        port: {{.PostgresPort}}
        user: {{.PostgresUser}}
        password: {{.PostgresPassword}}
        dbname: "inventory"