apiVersion: v1
kind: Secret
metadata:
  name: inventory-api-config
  namespace: {{.Namespace}}
type: Opaque
data:
  inventory-api-config.yaml: |
    server:
      http:
        address: 0.0.0.0:8081
      grpc:
        address: 0.0.0.0:9081
    authn:
      allow-unauthenticated: true
    authz:
      impl: allow-all
    eventing:
      eventer: stdout
      kafka:
    storage:
      database: postgres
      postgres:
        host: {{.PostgresHost}}
        port: {{.PostgresPort}}
        user: {{.PostgresUser}}
        password: {{.PostgresPassword}}
        dbname: "inventory"