apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name=inventory-api-certs
spec:
  ports:
  - name: http-server
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: grpc-server
    port: 9081
    protocol: TCP
    targetPort: 9081
  selector:
    app: inventory-api