# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusterglobalhubs.operator.open-cluster-management.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: multicluster-global-hub
          name: webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
