apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: global-hub-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: global-hub-operator-catalog
  sourceType: grpc
  grpcPodConfig: {}
  secrets:
  - global-hub-secret
  image: ${REGISTRY}/multicluster-global-hub-operator-catalog:v0.0.1
  publisher: global-hub-squad