apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  managedClusters: "5s"
  policies: "5s"
  hubClusterInfo: "60s"
  hubClusterHeartbeat: "60s"
  aggregationLevel: full
  enableLocalPolicies: "true"
