{{ if .InstallACMHub }}
{{ if .ACMImagePullSecretData }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .ACMImagePullSecretData }}
kind: Secret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
    global-hub.open-cluster-management.io/managed-by: global-hub
  annotations:
    "addon.open-cluster-management.io/deletion-orphan": ""
type: kubernetes.io/dockerconfigjson
{{ end }}
{{ end }}
