{{ if and .InstallACMHub .ImagePullSecretData }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .ImagePullSecretData }}
kind: Secret
metadata:
  name: {{ .ImagePullSecretName }} # default multiclusterhub-operator-pull-secret
  namespace: open-cluster-management
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
    global-hub.open-cluster-management.io/managed-by: global-hub
  annotations:
    "addon.open-cluster-management.io/deletion-orphan": ""
type: kubernetes.io/dockerconfigjson
{{ end }}
