{{ if .InstallACMHub }}
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
    global-hub.open-cluster-management.io/managed-by: global-hub
  annotations:
    "addon.open-cluster-management.io/deletion-orphan": ""
{{ end }}
