{{ if .InstallACMHub }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:klusterlet-work:agent:mgh
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - operatorgroups
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  - deletecollection
{{ end }}
