kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
