apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-global-hub-operator-aggregated-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-global-hub-operator-aggregated-clusterrole
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-operator
  namespace: multicluster-global-hub
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-global-hub-operator-aggregated-rolebinding
  namespace: multicluster-global-hub
roleRef:
  kind: Role
  name: multicluster-global-hub-operator-aggregated-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-operator
  namespace: multicluster-global-hub
