apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-global-hub-operator
  name: multicluster-global-hub-operator-metrics-service
  namespace: multicluster-global-hub
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: multicluster-global-hub-operator