apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-globalhub-operator
  name: multicluster-globalhub-operator-metrics-service
  namespace: open-cluster-management
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: multicluster-globalhub-operator