kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  creationTimestamp: null
  name: multicluster-globalhub-operator-console-setup-clusterrole
rules:
# role for patching ocm-mutating-webhook
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  resourceNames:
  - ocm-mutating-webhook
  verbs:
  - get
  - update
  - patch
# role for annotate multiclusterhub
- apiGroups:
  - "operator.open-cluster-management.io"
  resources:
  - multiclusterhubs
  verbs:
  - get
  - update
  - patch
  - list
  - watch
# role for annotate multiclusterengine
- apiGroups:
  - multicluster.openshift.io
  resources:
  - multiclusterengines
  verbs:
  - get
  - update
  - patch
  - list
  - watch
# role for delete console charts
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - subscriptions
  - channels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# role for install console chart
- apiGroups:
  - ''
  resources:
  - jobs
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "hive.openshift.io"
  resources:
  - clusterimagesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - config.openshift.io
  - console.openshift.io
  - project.openshift.io
  - tower.ansible.com
  resources:
  - infrastructures
  - consolelinks
  - projects
  - featuregates
  - ansiblejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.open-cluster-management.io
  resources:
  - baremetalassets
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterclaims
  - clusterdeployments
  - clusterpools
  - clusterimagesets
  - clusterprovisions
  - clusterdeprovisions
  - machinepools
  verbs:
  - list
  - watch
- verbs:
  - list
  - watch
  apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclustersets
  - managedclustersetbindings
  - clustercurators
  - placementdecisions
  - placements
- apiGroups:
  - internal.open-cluster-management.io
  resources:
  - managedclusterinfos
  verbs:
  - list
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs
  - discoveredclusters
  verbs:
  - list
  - watch
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  verbs:
  - list
  - watch
- apiGroups:
  - submarineraddon.open-cluster-management.io
  resources:
  - submarinerconfigs
  verbs:
  - list
  - watch
- apiGroups:
  - extensions.hive.openshift.io
  resources:
  - agentclusterinstalls
  verbs:
  - list
  - watch
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agents
  - infraenvs
  verbs:
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - list
  - watch
# role for install grc chart
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - update
  - patch
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - policy-encryption-key
  verbs:
  - patch
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
- apiGroups:
  - "*"
  resources:
  - "*/finalizers"
  verbs:
  - update
- apiGroups:
  - "apps.open-cluster-management.io"
  resources:
  - "*"
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - "*"
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "view.open-cluster-management.io"
  resources:
  - managedclusterviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "addon.open-cluster-management.io"
  resources:
  - "managedclusteraddons/status"
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  verbs:
  - patch
  - update
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - update
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests/approval
  verbs:
  - create
  - update
  - watch
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - signers
  verbs:
  - approve
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  resourceNames:
  - cert-policy-controller
  - config-policy-controller
  - governance-policy-framework
  - iam-policy-controller
  verbs:
  - patch
  - update
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  resourceNames:
  - open-cluster-management:cert-policy-controller-hub
  - open-cluster-management:config-policy-controller-hub
  - open-cluster-management:iam-policy-controller-hub
  - open-cluster-management:policy-framework-hub
  verbs:
  - patch
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  resourceNames:
  - open-cluster-management:cert-policy-controller-hub
  - open-cluster-management:config-policy-controller-hub
  - open-cluster-management:iam-policy-controller-hub
  - open-cluster-management:policy-framework-hub
  verbs:
  - patch
- apiGroups:
  - "tower.ansible.com"
  resources:
  - ansiblejobs
  verbs:
  - deletecollection
