# permissions for end users to view multiclusterglobalhubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterglobalhub-viewer-role
rules:
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - multiclusterglobalhubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hubofhubs.open-cluster-management.io
  resources:
  - multiclusterglobalhubs/status
  verbs:
  - get
