kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-global-hub:multicluster-global-hub-manager
  labels:
    name: multicluster-global-hub-manager
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-manager
  namespace: {{.Namespace}}
roleRef:
  kind: ClusterRole
  name: multicluster-global-hub:multicluster-global-hub-manager
  apiGroup: rbac.authorization.k8s.io
