{{ if .EnableGlobalResource }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: multicluster-global-hub-manager
  name: multicluster-global-hub-manager
  namespace: {{.Namespace}}
spec:
  port:
    targetPort: api-server
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: multicluster-global-hub-manager
    weight: 100
  wildcardPolicy: None
{{ end }}