apiVersion: v1
kind: Secret
metadata:
  name: {{.TransportConfigSecret}}
  namespace: {{.Namespace}}
  annotations:
    # todo put here or configmap
    za-log-level: {{.LogLevel}}
  labels:
    name: multicluster-global-hub-manager
type: Opaque
data:
  "kafka.yaml": {{.KafkaConfigYaml}}