kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-globalhub-agent
subjects:
- kind: ServiceAccount
  name: multicluster-globalhub-agent
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: multicluster-globalhub-agent
  apiGroup: rbac.authorization.k8s.io
