{{- if not .InstallHostedMode -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-global-hub-agent
  template:
    metadata:
      labels:
        name: multicluster-global-hub-agent
    spec:
      serviceAccountName: multicluster-global-hub-agent
      containers:
        - name: multicluster-global-hub-agent
          image: {{ .HoHAgentImage }}
          args:
            - '--zap-devel=true'
            - --pod-namespace=$(POD_NAMESPACE)
            - --leaf-hub-name={{ .LeafHubID }}
            - --kakfa-consumer-id={{ .LeafHubID }}
            - --enforce-hoh-rbac=false
            - --transport-type={{ .TransportType }}
            - --transport-format={{.TransportFormat}}
            - --kafka-bootstrap-server={{ .KafkaBootstrapServer }}
            - --kafka-ca-path=/kafka-ca/ca.crt
            - --transport-message-compression-type={{.MessageCompressionType}}
            - --lease-duration={{.LeaseDuration}}
            - --renew-deadline={{.RenewDeadline}}
            - --retry-period={{.RetryPeriod}}
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /kafka-ca
            name: kafka-ca
            readOnly: true
      volumes:
      - name: kafka-ca
        secret:
          secretName: kafka-ca-secret
{{- end -}}
