{{- if not .InstallHostedMode -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.KafkaClusterCASecret}}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: none
    name: {{.KafkaAgentSecretName}}
type: Opaque
data:
  "ca.crt": "{{.KafkaCACert}}"
{{- end -}}