apiVersion: v1
kind: ConfigMap
metadata:
  name: multicluster-global-hub-agent-config
  namespace: open-cluster-management-global-hub-system
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
data:
  managedClusters: "5s"
  policies: "5s"
  controlInfo: "60m"
  aggregationLevel: {{ .AggregationLevel }}
  enableLocalPolicies: "{{ .EnableLocalPolicies }}"