apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-event-exporter-config
  namespace: open-cluster-management-global-hub-system
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    maxEventAgeSeconds: 10
    metricsNamePrefix: "mcgh",
    kubeQPS: 60
    kubeBurst: 60
    # namespace: my-namespace-only # Omitting it defaults to all namespaces.
    route:
      # Main route
      routes:
        # This a final route for user messages
        - match:
            - kind: "Policy|ManagedCluster"
              receiver: "kafka"
    receivers:
      - name: "kafka"
        kafka:
          topic: "event"
          clientID: {{ .LeafHubID }}
          brokers:
            - {{ .KafkaBootstrapServer }}
          tls:
            enable: true
            caFile: /kafka-ca/ca.crt
            insecureSkipVerify: true
