apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-global-hub-system
  labels:
    addon.open-cluster-management.io/namespace: "true"
    addon.open-cluster-management.io/hosted-manifest-location: managed