apiVersion: v1
kind: ConfigMap
metadata:
  name: multicluster-global-hub-agent-config
  namespace: multicluster-global-hub-agent
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: managed
data:
  managedClusters: "5s"
  policies: "5s"
  hubClusterInfo: "60s"
  hubClusterHeartbeat: {{.AgentHeartbeatInteval}}
  aggregationLevel: {{ .AggregationLevel }}
  enableLocalPolicies: "{{ .EnableLocalPolicies }}"