apiVersion: v1
kind: Secret
metadata:
  name: {{.StorageConfigSecret}}
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
type: Opaque
data:
  "ca.crt": "{{.PostgresCACert}}"
  "database-url": "{{.DatabaseURL}}"
