apiVersion: v1
data:
  acm-global-policy-group-compliancy-overview.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "datasource",
              "uid": "grafana"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 5,
      "links": [
        {
          "asDropdown": false,
          "icon": "dashboard",
          "includeVars": true,
          "keepTime": true,
          "tags": [],
          "targetBlank": true,
          "title": "Global Hub - Offending Policies",
          "tooltip": "",
          "type": "link",
          "url": "d/b67e0727891f4121ae2dde09671520ae/global-hub-offending-policies?orgId=1"
        }
      ],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "grafana-postgresql-datasource",
            "uid": "${datasource}"
          },
          "description": "Aggregated policy group trend by standard, category, and control (Data updated once a day).",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "links": [
                {
                  "targetBlank": true,
                  "title": "View Offending Policies for $group group: ${__field.name}",
                  "url": "d/b67e0727891f4121ae2dde09671520ae/global-hub-offending-policies?orgId=1&from=${__value.time}&to=${__value.time}&${standard:queryparam}&${category:queryparam}&${control:queryparam}"
                }
              ],
              "mappings": [],
              "max": 1,
              "noValue": "Initial data load occurs after 0:00Z",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "percentunit",
              "unitScale": true
            },
            "overrides": []
          },
          "gridPos": {
            "h": 12,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 28,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "8.5.20",
          "targets": [
            {
              "datasource": {
                "uid": "${datasource}"
              },
              "editorMode": "code",
              "format": "time_series",
              "group": [],
              "metricColumn": "none",
              "rawQuery": true,
              "rawSql": "WITH data as(\n  WITH renamedata as (\n      SELECT\n        ch.compliance_date AS \"time\",\n        p.policy_standard AS \"standard\",\n        p.policy_category AS \"category\",\n        p.policy_control AS \"control\",\n        ch.compliance\n      FROM\n        local_spec.policies p\n      INNER JOIN\n        history.local_compliance ch ON p.policy_id = ch.policy_id\n      WHERE\n        $__timeFilter(ch.compliance_date)\n      AND\n        p.policy_standard ${standard_query:raw} AND p.policy_category ${category_query:raw} AND p.policy_control ${control_query:raw}\n      AND\n        ch.cluster_id IS NOT NULL\n  )\n  SELECT \n    time,\n    $group,\n    COUNT(CASE WHEN compliance = 'compliant' THEN 1 END) AS \"compliant\",\n    COUNT(CASE WHEN compliance = 'non_compliant' THEN 1 END) AS \"non_compliant\",\n    COUNT(CASE WHEN compliance = 'pending' THEN 1 END) AS \"pending\",\n    COUNT(CASE WHEN compliance = 'unknown' THEN 1 END) AS \"unknown\"\n  FROM\n    renamedata\n  GROUP BY (time, $group)\n)\nSELECT\n  time,\n  $group as \"metric\",\n  compliant::float / NULLIF((compliant::float + non_compliant + unknown + pending), 0) as \"value\"\nFROM\n  data\nORDER BY\n  time",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "sql": {
                "columns": [
                  {
                    "parameters": [],
                    "type": "function"
                  }
                ],
                "groupBy": [
                  {
                    "property": {
                      "type": "string"
                    },
                    "type": "groupBy"
                  }
                ],
                "limit": 50
              },
              "timeColumn": "time",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                }
              ]
            }
          ],
          "title": "Compliancy Trend (By $group)",
          "type": "timeseries"
        }
      ],
      "refresh": "",
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "Global-Hub-DataSource",
              "value": "P244538DD76A4C61D"
            },
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "datasource",
            "options": [],
            "query": "postgres",
            "queryValue": "",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": {
              "type": "grafana-postgresql-datasource",
              "uid": "${datasource}"
            },
            "definition": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n)\nSELECT\n  DISTINCT policy_standard\nFROM\n  local_spec.policies p\nJOIN\n  compcluster ch \nON\n p.policy_id = ch.policy_id\nWHERE\npolicy_standard IS NOT NULL;",
            "description": "Cluster policy standards",
            "hide": 0,
            "includeAll": true,
            "label": "Standard",
            "multi": true,
            "name": "standard",
            "options": [],
            "query": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n)\nSELECT\n  DISTINCT policy_standard\nFROM\n  local_spec.policies p\nJOIN\n  compcluster ch \nON\n p.policy_id = ch.policy_id\nWHERE\npolicy_standard IS NOT NULL;",
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 5,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": {
              "type": "grafana-postgresql-datasource",
              "uid": "${datasource}"
            },
            "definition": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n)\nSELECT\n  DISTINCT policy_category\nFROM\n  local_spec.policies p\nJOIN\n  compcluster ch \nON\n p.policy_id = ch.policy_id\nWHERE\n  policy_standard IN ($standard) \nAND\n  policy_category IS NOT NULL",
            "description": "Cluster policy categories",
            "hide": 0,
            "includeAll": true,
            "label": "Category",
            "multi": true,
            "name": "category",
            "options": [],
            "query": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n)\nSELECT\n  DISTINCT policy_category\nFROM\n  local_spec.policies p\nJOIN\n  compcluster ch \nON\n p.policy_id = ch.policy_id\nWHERE\n  policy_standard IN ($standard) \nAND\n  policy_category IS NOT NULL",
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 5,
            "type": "query"
          },
          {
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": {
              "type": "grafana-postgresql-datasource",
              "uid": "${datasource}"
            },
            "definition": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n)\nSELECT\n  DISTINCT policy_control\nFROM\n  local_spec.policies p\nJOIN\n  compcluster ch \nON\n p.policy_id = ch.policy_id\nWHERE\n  policy_standard IN ($standard)\nAND\n  policy_category IN ($category)\nAND\n  policy_control IS NOT NULL",
            "description": "Cluster policy controls",
            "hide": 0,
            "includeAll": true,
            "label": "Control",
            "multi": true,
            "name": "control",
            "options": [],
            "query": "WITH compcluster as(\n  SELECT DISTINCT policy_id\n  FROM\n  history.local_compliance ch\n  WHERE\n  $__timeFilter(ch.compliance_date)\n)\nSELECT\n  DISTINCT policy_control\nFROM\n  local_spec.policies p\nJOIN\n  compcluster ch \nON\n p.policy_id = ch.policy_id\nWHERE\n  policy_standard IN ($standard)\nAND\n  policy_category IN ($category)\nAND\n  policy_control IS NOT NULL",
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 5,
            "type": "query"
          },
          {
            "current": {
              "selected": false,
              "text": "standard",
              "value": "standard"
            },
            "description": "Filter priority for policy grouping on the x-axis.",
            "hide": 0,
            "includeAll": false,
            "label": "x-axis Group",
            "multi": false,
            "name": "group",
            "options": [
              {
                "selected": false,
                "text": "category",
                "value": "category"
              },
              {
                "selected": false,
                "text": "control",
                "value": "control"
              },
              {
                "selected": true,
                "text": "standard",
                "value": "standard"
              }
            ],
            "query": "category, control, standard",
            "queryValue": "",
            "skipUrlSync": false,
            "type": "custom"
          },
          {
            "current": {
              "selected": false,
              "text": " in ('NIST SP 800-53') ",
              "value": " in ('NIST SP 800-53') "
            },
            "datasource": {
              "type": "grafana-postgresql-datasource",
              "uid": "P244538DD76A4C61D"
            },
            "definition": "select case when length($$${standard}$$)>0 then $$ in ($standard) $$ else ' is null ' end",
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "standard_query",
            "options": [],
            "query": "select case when length($$${standard}$$)>0 then $$ in ($standard) $$ else ' is null ' end",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": false,
              "text": " in ('CM Configuration Management') ",
              "value": " in ('CM Configuration Management') "
            },
            "datasource": {
              "type": "grafana-postgresql-datasource",
              "uid": "P244538DD76A4C61D"
            },
            "definition": "select case when length($$${category}$$)>0 then $$ in ($category) $$ else ' is null ' end",
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "category_query",
            "options": [],
            "query": "select case when length($$${category}$$)>0 then $$ in ($category) $$ else ' is null ' end",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "current": {
              "selected": false,
              "text": " in ('CM-2 Baseline Configuration','CM-2 Baseline Configuration, CM-6 Configuration Settings') ",
              "value": " in ('CM-2 Baseline Configuration','CM-2 Baseline Configuration, CM-6 Configuration Settings') "
            },
            "datasource": {
              "type": "grafana-postgresql-datasource",
              "uid": "P244538DD76A4C61D"
            },
            "definition": "select case when length($$${control}$$)>0 then $$ in ($control) $$ else ' is null ' end",
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "control_query",
            "options": [],
            "query": "select case when length($$${control}$$)>0 then $$ in ($control) $$ else ' is null ' end",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-7d",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "utc",
      "title": "Global Hub - Policy Group Compliancy Overview",
      "uid": "9bb3bee6a17e47f9a231f6d77f2408fa",
      "version": 1,
      "weekStart": ""
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-acm-global-policy-group-compliancy-overview
  namespace: {{.Namespace}}
