apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-global-hub-grafana
  name: multicluster-global-hub-grafana-alerting
  namespace: {{.Namespace}}
spec:
  type: ClusterIP
  clusterIP: 'None'
  ports:
    - port: 9094
  selector:
    name: multicluster-global-hub-grafana
