apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: multicluster-global-hub-grafana
  name: multicluster-global-hub:multicluster-global-hub-grafana
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- verbs:
  - create
  apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
- verbs:
  - create
  apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews