apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: multicluster-global-hub-grafana
  name: multicluster-global-hub-grafana
  namespace: {{.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multicluster-global-hub-grafana
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-grafana
  namespace: {{.Namespace}}
