{{- if .EnableMetrics }}
apiVersion: v1
kind: Secret
metadata:
  name: multicluster-global-hub-grafana-sa-secret
  namespace: {{.Namespace}}
  annotations:
    kubernetes.io/service-account.name: "multicluster-global-hub-grafana"
type: kubernetes.io/service-account-token
{{- end }}
