apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{.Namespace}}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.grafana: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"multicluster-global-hub-grafana"}}'
  name: multicluster-global-hub-grafana
  labels:
    name: multicluster-global-hub-grafana