kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-globalhub-manager
  labels:
    name: multicluster-globalhub-manager
subjects:
- kind: ServiceAccount
  name: multicluster-globalhub-manager
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: multicluster-globalhub-manager
  apiGroup: rbac.authorization.k8s.io
