apiVersion: v1
kind: ConfigMap
metadata:
  name: multicluster-global-hub-rbac-ca-bundle
  namespace: {{.Namespace}}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    service: multicluster-global-hub-manager
