apiVersion: v1
kind: Secret
metadata:
  name: kafka-certs-secret
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
type: Opaque
data:
  "ca.crt": "{{.KafkaCACert}}"
  "client.crt": "{{.KafkaClientCert}}"
  "client.key": "{{.KafkaClientKey}}"