apiVersion: v1
kind: Secret
metadata:
  name: postgres-certs-secret
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
type: Opaque
data:
  "ca.crt": "{{.PostgresCACert}}"
