kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-global-hub-manager
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-manager
roleRef:
  kind: Role
  name: multicluster-global-hub-manager
  apiGroup: rbac.authorization.k8s.io
