{{ if .EnableGlobalResource }}
apiVersion: v1
kind: Secret
metadata:
  name: nonk8s-apiserver-cookie-secret
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
  annotations:
    skip-creation-if-exist: "true"
type: Opaque
stringData:
  session_secret: "{{.ProxySessionSecret}}"
{{ end }}
