apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-manager
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
    service: multicluster-global-hub-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-manager-certs
spec:
  ports:
  {{ if .EnableGlobalResource }}
  - port: 8443
    targetPort: oauth-proxy
    name: api-server
  {{ else }}
  - port: 8080
    targetPort: http-apiserver
    name: api-server
  {{ end }}  
  - port: 8384
    name: metrics
    targetPort: metrics
  selector:
    name: multicluster-global-hub-manager
---
{{ if .EnableGlobalResource }}
apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-webhook
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-webhook
    service: multicluster-global-hub-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-webhook-certs
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
    name: webhook-server
  selector:
    name: multicluster-global-hub-manager
{{ end }}
