apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-manager
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
    service: multicluster-global-hub-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-manager-certs
spec:
  ports:
  - port: 8080
    name: http
  selector:
    name: multicluster-global-hub-manager
