apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: multicluster-global-hub-manager
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-manager
spec:
  selector:
    matchLabels:
      name: multicluster-global-hub-manager
  endpoints:
  - port: metrics
    path: /metrics
    interval: 60s
