apiVersion: v1
kind: Service
metadata:
  name: multicluster-globalhub-manager
  namespace: open-cluster-management
  labels:
    name: multicluster-globalhub-manager
    service: multicluster-globalhub-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-globalhub-manager-certs
spec:
  ports:
  - port: 8080
    name: http
  selector:
    name: multicluster-globalhub-manager
