apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: multicluster-global-hub-manager
  namespace: openshift-monitoring # namespace where prometheus is running
  labels:
    name: multicluster-global-hub-manager
spec:
  namespaceSelector:
    matchNames:
    - {{.Namespace}}
  selector:
    matchLabels:
      name: multicluster-global-hub-manager
  endpoints:
  - port: metrics
    path: /metrics
    interval: 60s
