apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    name: {{.Name}}
type: Opaque
stringData:
  database-admin_user: "{{.PostgresAdminUser}}"
  database-admin-password: "{{.PostgresAdminUserPassword}}"
  database-readonly-user: "{{.PostgresReadonlyUsername}}"
  database-readonly-password: "{{.PostgresReadonlyUserPassword}}"
  database-uri: "{{.PostgresURI}}"
