apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-global-hub
      component: multicluster-global-hub-operator
      name: {{.Name}}
  template:
    metadata:
      labels:
        app: multicluster-global-hub
        component: multicluster-global-hub-operator
        name: {{.Name}}
    spec:
      containers:
      - env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-admin-password
              name: {{.Name}}
        - name: POSTGRESQL_SHARED_BUFFERS
          value: 64MB
        - name: POSTGRESQL_EFFECTIVE_CACHE_SIZE
          value: 128MB
        - name: WORK_MEM
          value: 16MB
        image: {{.PostgresImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: {{.Name}}
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
        {{- if .Resources.Limits }}
          limits:
            {{- range $key, $value := .Resources.Limits }}
            {{$key}}: {{.ToUnstructured}}
            {{- end }}
        {{- end }}
        {{- if .Resources.Requests }}
          requests:
            {{- range $key, $value := .Resources.Requests }}
            {{$key}}: {{.ToUnstructured}}
            {{- end }}
        {{- end }}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgresdb
          readOnly: false
        - mountPath: /opt/app-root/src/certs/
          name: postgresql-cert
        - mountPath: /opt/app-root/src/postgresql-cfg
          name: postgresql-cfg
        - mountPath: /opt/app-root/src/postgresql-start
          name: postgresql-start
      {{- if .EnablePostgresMetrics }}
      - name: prometheus-postgres-exporter
        args:
        - "--config.file=/etc/postgres_exporter.yml"
        - "--web.listen-address=:9187"
        - "--collector.stat_statements"
        env:
        - name: DATA_SOURCE_URI
          valueFrom:
            secretKeyRef:
              name: {{.Name}}
              key: database-uri
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: {{.Name}}
              key: database-admin_user
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: {{.Name}}
              key: database-admin-password
        image: {{.PostgresExporterImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        ports:
          - name: http
            containerPort: 9187
            protocol: TCP
        livenessProbe:
          initialDelaySeconds: 0
          timeoutSeconds: 3
          httpGet:
            path: /
            port: http
        readinessProbe:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          httpGet:
            path: /
            port: http
      {{- end }}
      serviceAccountName: {{.Name}}
      {{- if .ImagePullSecret }}
      imagePullSecrets:
        - name: {{.ImagePullSecret}}
      {{- end }}
      {{- if .NodeSelector }}
      nodeSelector:
        {{- range $key, $value := .NodeSelector}}
        "{{$key}}": "{{$value}}"
        {{- end}}
      {{- end }}
      {{- if .Tolerations }}
      tolerations:
        {{- range .Tolerations}}
        - key: "{{.Key}}"
          operator: "{{.Operator}}"
          value: "{{.Value}}"
          effect: "{{.Effect}}"
          {{- if .TolerationSeconds}}
          tolerationSeconds: {{.TolerationSeconds}}
          {{- end}}
        {{- end}}
      {{- end }}
      volumes:
      - name: postgresql-cfg
        configMap:
          defaultMode: 420
          name: {{.PostgresConfigName}}
      - name: postgresql-start
        configMap:
          defaultMode: 420
          name: {{.PostgresInitName}}
      - name: postgresql-cert
        secret:
          defaultMode: 416
          secretName: {{.PostgresCertName}}
  volumeClaimTemplates:
  - metadata:
      labels:
        app: multicluster-global-hub
        component: multicluster-global-hub-operator
        name: {{.Name}}
      name: postgresdb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{.StorageSize}}
      {{- if .StorageClass}}
      storageClassName: {{.StorageClass}}
      {{- end}}