apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    name: {{.Name}}
    service: {{.Name}}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{.PostgresCertName}}
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  {{- if .EnablePostgresMetrics }}
  - port: 80
    targetPort: 9187
    protocol: TCP
    name: http
  {{- end }}
  selector:
    name: {{.Name}}
