apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "hubofhubs.open-cluster-management.io/v1alpha1",
          "kind": "Config",
          "metadata": {
            "name": "config"
          },
          "spec": {
            "kafka": {
              "name": "kafka-secret"
            },
            "postgreSQL": {
              "name": "postgresql-secret"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: hub-of-hubs-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Config is the Schema for the configs API
      displayName: Config
      kind: Config
      name: configs.hubofhubs.open-cluster-management.io
      version: v1alpha1
  description: hub-of-hubs-operator defines the configuration for the hub-of-hubs
    installation with one custom resource.
  displayName: hub-of-hubs-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - policy.open-cluster-management.io
          resources:
          - policies
          - policies/status
          - policies/finalizers
          - placementbindings
          - placementbindings/finalizers
          verbs:
          - get
          - list
          - watch
          - update
          - patch
        - apiGroups:
          - apps.open-cluster-management.io
          resources:
          - placementrules
          - placementrules/status
          - subscriptionstatuses
          - subscriptionstatuses/status
          - subscriptionreports
          - subscriptionreports/status
          - subscriptions/finalizers
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - placements
          - placements/finalizers
          - placements/status
          - placementdecisions
          - placementdecisions/status
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          - events
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - managedclustersets
          - managedclustersets/finalizers
          - managedclustersetbindings
          - managedclustersetbindings/finalizers
          - placements
          - placements/finalizers
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - apps.open-cluster-management.io
          resources:
          - placementrules
          - placementrules/finalizers
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - hub-of-hubs.open-cluster-management.io
          resources:
          - configs
          - configs/finalizers
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - apps.open-cluster-management.io
          resources:
          - subscriptions
          - channels
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - app.k8s.io
          resources:
          - applications
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - clustermanagementaddons
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - addon.open-cluster-management.io
          resources:
          - managedclusteraddons
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - hypershiftdeployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - cluster.open-cluster-management.io
          resources:
          - managedclusters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - hubofhubs.open-cluster-management.io
          resources:
          - configs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hubofhubs.open-cluster-management.io
          resources:
          - configs/finalizers
          verbs:
          - update
        - apiGroups:
          - hubofhubs.open-cluster-management.io
          resources:
          - configs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - packages.operators.coreos.com
          resources:
          - packagemanifests
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - create
          - delete
          - get
          - list
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - work.open-cluster-management.io
          resources:
          - manifestworks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: hub-of-hubs-operator
      deployments:
      - label:
          name: hub-of-hubs-operator
        name: hub-of-hubs-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: hub-of-hubs-operator
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: hub-of-hubs-operator
              labels:
                name: hub-of-hubs-operator
            spec:
              containers:
              - args:
                - --leader-elect
                command:
                - hub-of-hubs-operator
                image: quay.io/stolostron/hub-of-hubs-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: hub-of-hubs-operator
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: hub-of-hubs-operator
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: hub-of-hubs-operator
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hub-of-hubs
  - multiple-hubs
  links:
  - name: Hub Of Hubs Operator
    url: https://github.com/stolostron/hub-of-hubs
  maintainers:
  - email: acm-contact@redhat.com
    name: acm-contact
  maturity: alpha
  provider:
    name: Red Hat, Inc
    url: https://github.com/stolostron/hub-of-hubs
  version: 0.0.1
