apiVersion: v1
kind: Secret
metadata:
  name: multicluster-global-hub-grafana-cookie-secret
  annotations:
    skip-creation-if-exist: "true"
type: Opaque
stringData:
  session_secret: {{.SessionSecret}}
  # session_secret: "aUzk54yCW8UdGeY3N7NT7w=="