apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: multicluster-globalhub-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: MultiClusterGlobalHub is the Schema for the multiclusterglobalhubs
        API
      displayName: Multi Cluster Global Hub
      kind: MultiClusterGlobalHub
      name: multiclusterglobalhubs.operator.open-cluster-management.io
      version: v1alpha1
  description: multicluster-globalhub-operator defines the configuration for the hub-of-hubs
    installation with one custom resource.
  displayName: multicluster-globalhub-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hub-of-hubs
  - multiple-hubs
  links:
  - name: Hub Of Hubs Operator
    url: https://github.com/stolostron/multicluster-globalhub
  maintainers:
  - email: acm-contact@redhat.com
    name: acm-contact
  maturity: alpha
  provider:
    name: Red Hat, Inc
    url: https://github.com/stolostron/multicluster-globalhub
  version: 0.0.1
