apiVersion: v1
kind: Secret
metadata:
  name: multicluster-global-hub-postgres
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-postgres
type: Opaque
stringData:
  database-admin_user: "{{.PostgresAdminUser}}"
  database-admin-password: "{{.PostgresAdminUserPassword}}"
  database-readonly-user: "{{.PostgresReadonlyUsername}}"
  database-readonly-password: "{{.PostgresReadonlyUserPassword}}"
  database-uri: "{{.PostgresURI}}"
