resources:
  - manager.yaml

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
# - files:
#   - controller_manager_config.yaml
#   name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/stolostron/multicluster-globalhub-operator
    newName: quay.io/stolostron/multicluster-globalhub-operator
    newTag: latest
