# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     name: multicluster-global-hub-operator
#   name: open-cluster-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-operator
  namespace: open-cluster-management
  labels:
    name: multicluster-global-hub-operator
spec:
  selector:
    matchLabels:
      name: multicluster-global-hub-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: multicluster-global-hub-operator
      labels:
        name: multicluster-global-hub-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - multicluster-global-hub-operator
        args:
        - --leader-elect
        image: quay.io/stolostron/multicluster-global-hub-operator:latest
        name: multicluster-global-hub-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_MULTICLUSTER_GLOBAL_HUB_MANAGER
          value: quay.io/stolostron/multicluster-global-hub-manager:latest
        - name: OPERAND_IMAGE_MULTICLUSTER_GLOBAL_HUB_AGENT
          value: quay.io/stolostron/multicluster-global-hub-agent:latest
        - name: OPERAND_IMAGE_MULTICLUSTER_GLOBAL_HUB_OPERATOR
          value: quay.io/stolostron/multicluster-global-hub-operator:latest
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: multicluster-global-hub-operator
      terminationGracePeriodSeconds: 10
