# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     name: multicluster-globalhub-operator
#   name: open-cluster-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-globalhub-operator
  namespace: open-cluster-management
  labels:
    name: multicluster-globalhub-operator
spec:
  selector:
    matchLabels:
      name: multicluster-globalhub-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: multicluster-globalhub-operator
      labels:
        name: multicluster-globalhub-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - multicluster-globalhub-operator
        args:
        - --leader-elect
        image: quay.io/stolostron/multicluster-globalhub-operator:latest
        name: multicluster-globalhub-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: multicluster-globalhub-operator
      terminationGracePeriodSeconds: 10
