apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-postgres
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-postgres
    service: multicluster-global-hub-postgres
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-postgres-certs
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
    protocol: TCP
  selector:
    name: multicluster-global-hub-postgres
