apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: global-hub-kafka-user
  namespace: multicluster-global-hub
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls