apiVersion: batch/v1
kind: Job
metadata:
  name: multicluster-global-hub-agent-applier
  namespace: {{.HostedClusterName}}
spec:
  template:
    spec:
      containers:
      - name: applier
        image: {{.HoHAgentImage}}
        imagePullPolicy: Always
        command: ["/usr/local/bin/applier"]
        args:
        - --hub-version={{.HubVersion}}
        - --kubeconfig=/var/run/secrets/hypershift/kubeconfig
        volumeMounts:
        - mountPath: /var/run/secrets/hypershift
          name: kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: service-network-admin-kubeconfig
      restartPolicy: OnFailure

