kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-global-hub:multicluster-global-hub-agent
rules:
- apiGroups:
  - "policy.open-cluster-management.io"
  resources:
  - placementbindings
  - policies
  - policyautomations
  - policysets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placements
  - managedclustersets
  - managedclustersetbindings
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - managedclusters/finalizers
  - placementdecisions
  - placementdecisions/finalizers
  - placements
  - placements/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - clusterclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - configmaps
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - internal.open-cluster-management.io
  resources:
  - managedclusterinfos
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - placementrules
  - subscriptionreports
  verbs:
  - get
  - list
  - patch
  - update
  - watch
