{{- if .InstallHostedMode -}}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-certs-secret
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
type: Opaque
data:
  "ca.crt": "{{.KafkaCACert}}"
  "client.crt": "{{.KafkaClientCert}}"
  "client.key": "{{.KafkaClientKey}}"
{{- end -}}
