{{- if .InstallHostedMode -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
subjects:
- kind: ServiceAccount
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
roleRef:
  kind: Role
  name: multicluster-global-hub-agent
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
