{{ if .InstallHostedMode }}
kind: Job
apiVersion: batch/v1
metadata:
  name: multicluster-global-hub-agent-cleanup
  namespace: {{ .AddonInstallNamespace }}
  labels:
    "open-cluster-management.io/addon-pre-delete": ""
    "addon.open-cluster-management.io/hosted-manifest-location": "hosting"
spec:
  manualSelector: true
  selector:
    matchLabels:
      job: multicluster-global-hub-agent-cleanup
  template:
    metadata:
      labels:
        job: multicluster-global-hub-agent-cleanup
    spec:
      serviceAccountName: multicluster-global-hub-agent
      restartPolicy: Never
      containers:
      - name: multicluster-global-hub-agent
        image: {{ .HoHAgentImage }}
        imagePullPolicy: {{.ImagePullPolicy}}
        args:
          - --kubeconfig=/var/run/secrets/managed/kubeconfig
          - --pod-namespace=$(POD_NAMESPACE)
          - --leaf-hub-name={{ .LeafHubID }}
          - --terminating=true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /var/run/secrets/managed
          name: kubeconfig
          readOnly: true
      {{ if .ImagePullSecretName }}
      imagePullSecrets:
        - name: {{ .ImagePullSecretName }}
      {{ end }}
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: external-managed-kubeconfig
{{ end }}