{{ if .InstallHostedMode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-global-hub-agent
  template:
    metadata:
      labels:
        name: multicluster-global-hub-agent
    spec:
      serviceAccountName: multicluster-global-hub-agent
      containers:
        - name: multicluster-global-hub-agent
          image: {{ .HoHAgentImage }}
          imagePullPolicy: {{ .ImagePullPolicy }}
          args:
            - --kubeconfig=/var/run/secrets/managed/kubeconfig
            - --pod-namespace=$(POD_NAMESPACE)
            - --leaf-hub-name={{ .LeafHubID }}
            - --kafka-consumer-id={{ .LeafHubID }}
            - --enforce-hoh-rbac=false
            - --transport-type={{ .TransportType }}
            - --kafka-bootstrap-server={{ .KafkaBootstrapServer }}
            - --kafka-ca-cert-path=/kafka-certs/ca.crt
            - --kafka-client-cert-path=/kafka-certs/client.crt
            - --kafka-client-key-path=/kafka-certs/client.key
            - --transport-message-compression-type={{.MessageCompressionType}}
            - --lease-duration={{.LeaseDuration}}
            - --renew-deadline={{.RenewDeadline}}
            - --retry-period={{.RetryPeriod}}
            - --enable-global-resource={{.EnableGlobalResource}}
          env:
            # - name: KUBECONFIG
            #   value: /var/run/secrets/hypershift/kubeconfig
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /var/run/secrets/managed
            name: kubeconfig
            readOnly: true
          - mountPath: /kafka-certs
            name: kafka-certs
            readOnly: true
      {{ if .ImagePullSecretName }}
      imagePullSecrets:
        - name: {{ .ImagePullSecretName }}
      {{ end }}
      nodeSelector:
        {{- range $key, $value := .NodeSelector}}
        "{{$key}}": "{{$value}}"
        {{- end}}
      tolerations:
        {{- range .Tolerations}}
        - key: "{{.Key}}"
          operator: "{{.Operator}}"
          value: "{{.Value}}"
          effect: "{{.Effect}}"
          {{- if .TolerationSeconds}}
          tolerationSeconds: {{.TolerationSeconds}}
          {{- end}}
        {{- end}}
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: external-managed-kubeconfig
      - name: kafka-certs
        secret:
          secretName: kafka-certs-secret
{{ end }}