{{- if .InstallHostedMode -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-global-hub-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-global-hub-agent
  template:
    metadata:
      labels:
        name: multicluster-global-hub-agent
    spec:
      serviceAccountName: multicluster-global-hub-agent
      containers:
        - name: multicluster-global-hub-agent
          image: {{ .HoHAgentImage }}
          imagePullPolicy: {{ .ImagePullPolicy }}
          args:
            - --kubeconfig=/var/run/secrets/managed/kubeconfig
            - '--zap-devel=true'
            - --pod-namespace=$(POD_NAMESPACE)
            - --leaf-hub-name={{ .LeafHubID }}
            - --kakfa-consumer-id={{ .LeafHubID }}
            - --enforce-hoh-rbac=false
            - --transport-type={{ .TransportType }}
            - --transport-format={{.TransportFormat}}
            - --kafka-bootstrap-server={{ .KafkaBootstrapServer }}
            - --kafka-ca-path=/kafka-ca/ca.crt
            - --transport-message-compression-type={{.MessageCompressionType}}
            - --lease-duration={{.LeaseDuration}}
            - --renew-deadline={{.RenewDeadline}}
            - --retry-period={{.RetryPeriod}}
          env:
            # - name: KUBECONFIG
            #   value: /var/run/secrets/hypershift/kubeconfig
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                 apiVersion: v1
                 fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              value: "open-cluster-management"
              # valueFrom:
              #   fieldRef:
              #    apiVersion: v1
              #    fieldPath: metadata.namespace
          volumeMounts:
          - mountPath: /var/run/secrets/managed
            name: kubeconfig
            readOnly: true
          - mountPath: /kafka-ca
            name: kafka-ca
            readOnly: true
      imagePullSecrets:
        - name: {{ .ImagePullSecretName }}
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: external-managed-kubeconfig
      - name: kafka-ca
        secret:
          secretName: kafka-ca-secret
{{- end -}}