{{- if .InstallHostedMode -}}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ca-secret
  namespace: {{ .AddonInstallNamespace }}
  labels:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
type: Opaque
data:
  "ca.crt": "{{.KafkaCACert}}"
{{- end -}}
