apiVersion: batch/v1
kind: Job
metadata:
  name: multicluster-globalhub-console-cleanup
  namespace: open-cluster-management
  labels:
    name: multicluster-globalhub-console
spec:
  template:
    spec:
      serviceAccountName: multicluster-globalhub-operator
      containers:
      - name: console-cleanup
        image: {{.Image}}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "/tmp/console-script/console-cleanup.sh"]
        env:
        # add this env to resolve https://github.com/helm/helm/issues/11012
        - name: HOME
          value: "/tmp"
        volumeMounts:
        - name: console-script
          mountPath: /tmp/console-script
      volumes:
      - name: console-script
        configMap:
          name: multicluster-globalhub-console-script
          defaultMode: 0755
      restartPolicy: Never
